version: '2'
services:
  app:
    container_name: o9000
    image: eboraas/laravel:latest
    pid: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Dev-Project-1/app/:/var/www/laravel/app/
      - ./Dev-Project-1/public/:/var/www/laravel/public/
    privileged: true 
  DB:
    image: mysql:8.0
    depends_on:
      - app
  Cache:
    image: redis:3.2.0
    depends_on:
      - app


volumes: ./Dev-Project-1/: